name: Stale Issue Checker

on:
  schedule:
    - cron: 0 0 * * *

jobs:
  stale-checker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup labeling script
        run: cd .github/labeler && npm install

      - name: Fetch issues
        id: issues
        uses: octokit/request-action@v2.x
        with:
          route: GET /repos/{owner}/{repo}/issues
          owner: pieces-app
          repo: support
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run stale issue checker
        run: node .github/stale-issue-checker/index.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUES: ${{  steps.issues.outputs.data }}
