name: Run Support Triage Bot

on:
  issues:
    types: [opened]

permissions:
  issues: write
  contents: read

jobs:
  run-private-script:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Python 3.9
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Checkout Private Repository
      uses: actions/checkout@v4
      with:
        repository: pieces-app/support_automation
        token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        path: support_automation

    - name: Install Dependencies
      run: |
        pip install -r support_automation/requirements.txt

    - name: Run Python Script
      env:
        SUPPORT_BOT_APP_ID: ${{ secrets.SUPPORT_BOT_APP_ID }}
        SUPPORT_BOT_INSTALLATION_ID: ${{ secrets.SUPPORT_BOT_INSTALLATION_ID }}
        SUPPORT_BOT_PRIVATE_KEY: ${{ secrets.SUPPORT_BOT_PRIVATE_KEY }}
        SUPPORT_TRIAGE_BOT: ${{ secrets.SUPPORT_TRIAGE_BOT }}
      run: |
        python support_automation/triage_bot/main.py process ${{ github.repository }} ${{ github.event.issue.number }}

    - name: Always clean up resources
      if: always()
      run: |
        rm -rf ~/.ssh
        rm -rf support_automation
        unset SUPPORT_BOT_APP_ID
        unset SUPPORT_BOT_INSTALLATION_ID
        unset SUPPORT_BOT_PRIVATE_KEY
        unset SUPPORT_TRIAGE_BOT
